# Discord Channel IDs
servers:
  server1:  # NC. Discord
    token: ${NC_BOT_TOKEN}  # Reference environment variable
    timerboard: 1346620736055410750  # Channel where timer list is displayed
    commands: 1346620859988574351    # Channel where commands are accepted
    citadel_attacked: 1092818946895384576  # Channel for citadel attack notifications
    citadel_info: 1092818260937953330  # Channel for citadel status updates
    sov: 1092823745778962442  # Channel for sov notifications
    skyhooks: 1092823070651207740  # Channel for skyhook reinforcement notifications
  server2:  # Second Discord
    token: ${SECOND_BOT_TOKEN}  # Reference environment variable
    timerboard: 1371980890397343885  # Channel where timer list is displayed
    commands: 1371980907346526338    # Channel where commands are accepted
    citadel_attacked: null  # Optional
    citadel_info: null     # Optional

# Timer Settings
timezone: 'UTC'                    # Timezone for all timer operations
check_interval: 60                 # How often to check timers (seconds)
notification_time: 60              # When to notify before timer (minutes)
expiry_time: 60                   # How long to keep expired timers (minutes)

# Bot Settings
command_prefix: '!'                # Prefix for bot commands 